version: '3.7'
services:
  db:
    image: 'postgres:11'
    container_name: 'CSI2132_Postgres_container'
    volumes:
      - sql_data:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: CSI2132_Postgres_container
    networks:
      - default
  frontend: 
    build:
      context: ./frontend
    container_name: 'CSI2132_Frontend'
    expose:
      - 3000
    ports: 
      - 3000:3000
    volumes: 
      - frontend:/app
    depends_on:
      - backend
      - db
    network_mode: host
  backend: 
    build:
      context: ./backend
    container_name: 'CSI2132_Backend'
    expose: 
      - 1234
    ports:
      - 1234:1234
    links:
      - db
    depends_on:
      - db
    networks:
      - default
  init: 
    build:
      context: ./init
    container_name: 'CSI2132_Data_Initializer'
    links:
      - db
    depends_on:
      - db
    networks:
      - default
volumes:
  sql_data:
  frontend: