version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "CSI2132_Postgres_container"
    ports:
      - "54320:5432"
    volumes:
      - sql_data:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: CSI2132_Postgres_container
  frontend: 
    image: "node:10"
    container_name: "CSI2132_Frontend"
    ports: 
      - "3000:3000"
    volumes: 
      - app:/app
volumes:
  sql_data: