version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "CSI2132_Postgres_container"
    ports:
      - "54320:5432"
    volumes:
      - sql_data:/var/lib/postgresql/data
    environment: 
      POSTGRES_HOST_AUTH_METHOD: trust
volumes:
  sql_data: